forum_demo/config/routes.rb
ForumDemo::Application.routes.draw do
  get "boards1/$"

  get "boards1/rails"

  get "boards1/g"

  get "boards1/controller"

  get "boards1/posts1"

  resources :posts

  resources :borads

  resources :posts1
  
  resources :borads1

root :to => "pages#welcome"

end

forum_demo/app/models/board1.rb
class Board1 < ActiveRecord::Base
  # attr_accessible :title, :body
end

forum_demo/app/models/borad.rb
class Borad < ActiveRecord::Base
  attr_accessible :name
end

forum_demo/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
end

forum_demo/app/models/post1.rb
class Post1 < ActiveRecord::Base
  # attr_accessible :title, :body
end

forum_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

forum_demo/app/controllers/boards1_controller.rb
class Boards1Controller < ApplicationController
  def $
  end

  def rails
  end

  def g
  end

  def controller
  end

  def posts1
  end
end

forum_demo/app/controllers/borads_controller.rb
class BoradsController < ApplicationController
  # GET /borads
  # GET /borads.json
  def index
    @borads = Borad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @borads }
    end
  end

  # GET /borads/1
  # GET /borads/1.json
  def show
    @borad = Borad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @borad }
    end
  end

  # GET /borads/new
  # GET /borads/new.json
  def new
    @borad = Borad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @borad }
    end
  end

  # GET /borads/1/edit
  def edit
    @borad = Borad.find(params[:id])
  end

  # POST /borads
  # POST /borads.json
  def create
    @borad = Borad.new(params[:borad])

    respond_to do |format|
      if @borad.save
        format.html { redirect_to @borad, :notice => 'Borad was successfully created.' }
        format.json { render :json => @borad, :status => :created, :location => @borad }
      else
        format.html { render :action => "new" }
        format.json { render :json => @borad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /borads/1
  # PUT /borads/1.json
  def update
    @borad = Borad.find(params[:id])

    respond_to do |format|
      if @borad.update_attributes(params[:borad])
        format.html { redirect_to @borad, :notice => 'Borad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @borad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /borads/1
  # DELETE /borads/1.json
  def destroy
    @borad = Borad.find(params[:id])
    @borad.destroy

    respond_to do |format|
      format.html { redirect_to borads_url }
      format.json { head :no_content }
    end
  end
end

forum_demo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

class PagesController < AppplicationController
	def welcome
	end
end

forum_demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

forum_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

forum_demo/app/helpers/boards1_helper.rb
module Boards1Helper
end

forum_demo/app/helpers/borads_helper.rb
module BoradsHelper
end

forum_demo/app/helpers/pages_helper.rb
module PagesHelper
end

forum_demo/app/helpers/posts_helper.rb
module PostsHelper
end

forum_demo/app/views/boards1/$.html.erb
<h1>Boards1#$</h1>
<p>Find me in app/views/boards1/$.html.erb</p>

forum_demo/app/views/boards1/controller.html.erb
<h1>Boards1#controller</h1>
<p>Find me in app/views/boards1/controller.html.erb</p>

forum_demo/app/views/boards1/g.html.erb
<h1>Boards1#g</h1>
<p>Find me in app/views/boards1/g.html.erb</p>

forum_demo/app/views/boards1/posts1.html.erb
<h1>Boards1#posts1</h1>
<p>Find me in app/views/boards1/posts1.html.erb</p>

forum_demo/app/views/boards1/rails.html.erb
<h1>Boards1#rails</h1>
<p>Find me in app/views/boards1/rails.html.erb</p>

forum_demo/app/views/borads/_form.html.erb
<%= form_for(@borad) do |f| %>
  <% if @borad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borad.errors.count, "error") %> prohibited this borad from being saved:</h2>

      <ul>
      <% @borad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

forum_demo/app/views/borads/edit.html.erb
<h1>Editing borad</h1>

<%= render 'form' %>

<%= link_to 'Show', @borad %> |
<%= link_to 'Back', borads_path %>

forum_demo/app/views/borads/index.html.erb
<h1>Listing borads</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @borads.each do |borad| %>
  <tr>
    <td><%= borad.name %></td>
    <td><%= link_to 'Show', borad %></td>
    <td><%= link_to 'Edit', edit_borad_path(borad) %></td>
    <td><%= link_to 'Destroy', borad, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Borad', new_borad_path %>

forum_demo/app/views/borads/new.html.erb
<h1>New borad</h1>

<%= render 'form' %>

<%= link_to 'Back', borads_path %>

forum_demo/app/views/borads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @borad.name %>
</p>


<%= link_to 'Edit', edit_borad_path(@borad) %> |
<%= link_to 'Back', borads_path %>

forum_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

forum_demo/app/views/pages/welcome.html.erb
Hello World!

forum_demo/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

forum_demo/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

forum_demo/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

forum_demo/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

forum_demo/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>